site_name: GameDuo
docs_dir: docs
site_dir: site

theme:
  name: material
  language: pt-BR
  icon:
    logo: material/controller-classic
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Ativar modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Ativar modo claro
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips

plugins:
  - search:
      lang: pt

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - tables
  - admonition
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - Cenário Atual do Cliente e do Negócio: visao-produto/cenario-atual.md
      - Solução Proposta: visao-produto/solucao-proposta.md
